# install bind9 service 
# ---
- name: install bind9
  apt: pkg=bind9 state=installed

- name: deploy named.conf.local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local
  notify:
    - restart bind9

- name: deploy named.conf.options
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - restart bind9

- name: create named.conf.ffms
  template: src=named.conf.ffms.j2 dest=/etc/bind/named.conf.ffms
  notify:
    - restart bind9

- name: create named.conf.freifunk-muensterland
  template: src=named.conf.freifunk-muensterland.j2 dest=/etc/bind/named.conf.freifunk-muensterland
  notify:
    - restart bind9
  when: "{{is_external_nameserver is defined and is_external_nameserver}}"

- name: create named.conf
  template: src=named.conf.j2 dest=/etc/bind/named.conf
  notify:
    - restart bind9

- name: create own db file for each subdomaene
  template: src=db.ffms.j2 dest=/etc/bind/db.domaene-{{item}}.ffms
  notify:
    - restart bind9
  with_items: "{{domaenenliste | default([])}}"
  when: "{{domaenenliste is defined}}"

