---
# Pakete installieren

- name: Abhängigkeiten von ffmap-backend installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - python3
    - python3-networkx
    - jq

- name: git für ffmap-backend
  git: repo=https://github.com/FreiFunkMuenster/ffmap-backend.git dest=/usr/src/ffmap-backend force=yes version=dcd6609030e32ebbf73692e78e7a2426ab1efdc4

- name: git für tools
  git: repo=https://github.com/FreiFunkMuenster/tools.git dest=/usr/src/tools force=yes version=c6cad7f46d44859174faf47f388ff8183ab45273

