---
# Sample config needs to be set in host_vars of backbone server only
- name: Create interfaces - tunnels to ffms supernodes
  template: src="gre_ffms.j2" dest="/etc/network/interfaces.d/41_gre_ffms.cfg"
  notify: restart networking

- name: Create interfaces - tunnels between backbones
  template: src="gre_interbackbone.j2" dest="/etc/network/interfaces.d/42_gre_interbackbone.cfg"
  notify: restart networking

- name: Routingtabelle 42 auch ffnet nennen
  lineinfile: dest="/etc/iproute2/rt_tables" line="42   ffnet"

#append line in interfaces file for reading additional config files
- name: let read interfaces.d from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify: restart networking
