 - name: Schl端ssel f端r Bird hinzuf端gen
   apt_key: keyserver=keyserver.ubuntu.com id=AC0E47584A7A714D

 - name: Bird-Repo hinzuf端gen
   apt_repository:
         repo: "deb http://bird.network.cz/debian/ jessie main"
         state: present

 - name: Bird installieren
   apt:
         pkg: "{{item}}"
         update_cache: yes
         state: installed
   with_items:
         - bird
         - bird6

 - name: bird automatisch starten
   service: name=bird enabled=yes

 - name: bird6 automatisch starten
   service: name=bird6 enabled=yes

 - name: Spezifischere Routen aus DHCP-Bereich berechnen
   local_action: shell ipcalc {{ domaenenliste[item].dhcp_start }} - {{ domaenenliste[item].dhcp_ende}} |grep -v "deaggregate"|sed -e 's/\(^.*$\)/route \1 via "bat{{item}}";/g'
   always_run: yes
   changed_when: false
   register: spezifische_Routen
   with_items: "{{domaenenliste}}"

 - name: configure bird.conf
   template: src=bird.conf.j2 dest=/etc/bird/bird.conf
   notify:
    - restart bird

 - name: configure bird6.conf
   template: src=bird6.conf.j2 dest=/etc/bird/bird6.conf
   notify:
    - restart bird6

 - name: bird aktivieren und starten
   service: name=bird state=started enabled=yes

 - name: bird6 aktivieren und starten
   service: name=bird6 state=started enabled=yes

 - name: bird per Shellbefehl aktivieren (Bug Ansible)
   shell: systemctl enable bird
   changed_when: false

 - name: bird6 per Shellbefehl aktivieren (Bug Ansible)
   shell: systemctl enable bird6
   changed_when: false
